### PR TITLE
Add domain, websocket and SSL

### PR DESCRIPTION
**Pull request by Krakinou**
In relation with #3 I added some options so that:
- it is now possible to use a domain and a path (although I only tested root domain)
- both websocket, direct port and ssl port are available, user just need to tweak the config file

 Unfortunately, adding a domain means it's not possible to upgrade directly from previous version as it requires user input, so I also added a check in the upgrade script.

I did not update the documentation, it may be a good idea though...

It's not thouroughly tested but it's based on the config I use on my server, so it should work

### CODE REVIEW

**Comment by Krakinou** [comment]
!testme

**Comment by Krakinou** [comment]
Hi,
Is it still maintained?

**Comment by Krakinou** [comment]
Hello
Still maintained?

**Comment by Salamandar** [comment]
Hi, I rebased your branch after the move to packagingv2.

**Comment by Salamandar** [comment]
Reopening

**Comment by Salamandar** [comment]
Grrr did not work. I made a new merge request.

**Pull request closed without merging**
